Flag --validation has been deprecated, this arg is no longer used, all resources are validated using server-side apply dry-run
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

sadadaddsad
metadata:
  name: flux-sample-app
  namespace: flux-system
spec:
aafafdsfsd
adfafa
  interval: 5m0s
  path: "./kustomize"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-sample-app

