apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-app
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: flux-sample-app-example
      version: '0.1.1'
      sourceRef:
        kind: HelmRepository
        name: helm-app
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    image:
      repository: 550945418071.dkr.ecr.eu-west-1.amazonaws.com/flux-sample-app
      tag: main-3ef16ec487b876823ed1e6ec89ccd2220908d662
      