apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-app
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: flux-sample-app-example
      version: '0.1.x'
      sourceRef:
        kind: HelmRepository
        name: helm-app
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2